version: '3.9'
services:
  melodic:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ros/melodic:latest
    container_name: melodic_container
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw