version: '3.9'
services:
  ros:
    build: 
      context: .
      dockerfile: Dockerfile
    image: skrjtech/khi_robot:noetic
    container_name: ros_noetic
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ../..
        target: /ws
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1 
      memlock: 8428281856
    network_mode: host