version: '3.9'
services:
  ros:
    image: skrjtech/khi_robot:melodic
    container_name: ros_melodic
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ../../archives/khiRobotPack
        target: /khi_robot/src/khiRobotPack
      - type: bind
        source: ../..
        target: /ws
    working_dir: /khi_robot