version: '3.9'
services:
  ros:
    build: 
      context: .docker/melodic/
      dockerfile: Dockerfile
    image: skrjtech/khi_robot:melodic
    container_name: ros_melodic
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1 
      memlock: 8428281856
    network_mode: host